### ISSUE TITLE
Project does not run in Chrome

### ISSUE THREAD

**Issue by jsimonson2013** [Madison-SDC/360WebViewer#2]
Opening the test.html file in Firefox works while opening the file in Chrome does not. Instead it gives the alert "Webgazer works only over https. If you are doing development locally you need to setup a local server" then does not run webgazer.

**Comment by MatthewTDuff** [comment]
Found the line where the error is happening inside of Webgazer. (line 10548)
        if (window.location.protocol !== 'https:' && window.location.hostname !== 'localhost' && window.chrome){
            alert("WebGazer works only over https. If you are doing local development you need to run a local server.");
        }
According to the below listed website, Chrome only wants things from the localhost. I don't know much about this type of thing, but it seems once we have a back-end this will clear up, or at the very least will be an easy fix. Anyone more knowledgeable on this is welcome to tell me otherwise, though. Zach said using Node could be a good temporary solution?
https://webrtchacks.com/chrome-secure-origin-https/

**Comment by jsimonson2013** [comment]
Closing for now
